# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(PipelineLevelVarible)  build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build SecondJob
    - bash: echo java -version
    - bash: echo mvn -version
    - bash: ls -R echo $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)' 
    - bash: ls -R echo $(Build.ArtifactStagingDirectory)

